name: pulumi-k8s
description: A minimal Kubernetes Python Pulumi program
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-python
